spring:
  datasource:
    url: jdbc:mysql://15.164.241.176:3306/celuveat
    username: mallang
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        highlight_sql: true
#
    hibernate:
      ddl-auto: validate

cors:
  allowedOrigins: http://localhost:3000

oauth:
  kakao:
    client_id:
    redirect_uri:
    client_secret:
    scope:
    admin_key:
  naver:
    client_id:
    redirect_uri:
    client_secret:
    scope:
    state:
  google:
    client_id:
    redirect_uri:
    client_secret:
    scope:

server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: false
        secure: false
